name: Patch IPA with Frida (MediaFire/GitHub)

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare workspace
        run: |
          mkdir -p work
          cd work
          curl -L -o crssplay_frida_localpatched.ipa "https://github.com/ColtonDavis/will-work/releases/download/1/crssplay_frida_localpatched.ipa"
          curl -L -o frida-gadget.dylib "https://github.com/ColtonDavis/will-work/releases/download/1/frida-gadget-17.3.2-ios-universal.dylib"
          ls -lh

      - name: Extract IPA (robust + diagnostics)
        run: |
          set -e
          cd work
          rm -rf work_unzip || true
          mkdir -p work_unzip
          echo "Attempting extraction with ditto..."
          if ditto -x -k crssplay_frida_localpatched.ipa work_unzip; then
            echo "ditto extraction succeeded."
          else
            echo "ditto failed, fallback to unzip..."
            unzip -o crssplay_frida_localpatched.ipa -d work_unzip || true
          fi

          echo "Directory tree (depth=4):"
          find work_unzip -maxdepth 4 -ls || true

          # find Payload ANYWHERE under work_unzip
          PAYLOAD_DIR=$(find work_unzip -type d -name "Payload" | head -n1 || true)
          if [ -z "$PAYLOAD_DIR" ]; then
            echo "ERROR: Payload folder not found. Dumping tree for debug:"
            find work_unzip -maxdepth 10 -ls || true
            exit 3
          fi
          echo "✅ Payload detected at: $PAYLOAD_DIR"
          ls -la "$PAYLOAD_DIR" || true
          echo "$PAYLOAD_DIR" > ../payload_path.txt

      - name: Copy Frida dylib into app Frameworks
        run: |
          set -e
          cd work
          PAYLOAD_DIR=$(cat ../payload_path.txt)
          APP_PATH=$(find "$PAYLOAD_DIR" -type d -name "*.app" | head -n1)
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: No .app found under $PAYLOAD_DIR"
            exit 2
          fi
          echo "App found: $APP_PATH"

          mkdir -p "$APP_PATH/Frameworks"
          cp frida-gadget.dylib "$APP_PATH/Frameworks/frida-gadget.dylib"
          chmod 755 "$APP_PATH/Frameworks/frida-gadget.dylib"
          ls -la "$APP_PATH/Frameworks"

      - name: Ensure optool (prebuilt or build from source)
        run: |
          set -e
          cd work
          if [ ! -f optool ]; then
            echo "Downloading prebuilt optool..."
            curl -L -o optool.zip "https://github.com/alexzielenski/optool/releases/download/0.1/optool.zip"
            unzip -o optool.zip || true
            chmod +x optool || true
          fi
          ./optool -h || true

      - name: Inject LC_LOAD_DYLIB into main executable
        run: |
          set -e
          cd work
          PAYLOAD_DIR=$(cat ../payload_path.txt)
          APP_PATH=$(find "$PAYLOAD_DIR" -type d -name "*.app" | head -n1)
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: No .app found under $PAYLOAD_DIR"
            exit 2
          fi
          EXECUTABLE="$APP_PATH/dfxm"
          echo "Injecting into: $EXECUTABLE"
          ./optool install -c load -p "@executable_path/Frameworks/frida-gadget.dylib" -t "$EXECUTABLE"

      - name: Repack IPA
        run: |
          set -e
          cd work
          rm -f ../patched.ipa
          cd work_unzip
          zip -qr ../patched.ipa .
          cd ..
          ls -lh patched.ipa

      - name: Upload patched IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: patched-ipa
          path: work/patched.ipa
