
name: Patch IPA with Frida (Release assets)

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: macos-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare workspace
        run: |
          rm -rf work work_unzip || true
          mkdir -p work work_unzip

      - name: Download IPA and dylib (from Releases)
        run: |
          cd work
          curl -L -o crssplay_frida_localpatched.ipa "https://github.com/ColtonDavis/will-work/releases/download/1/crssplay_frida_localpatched.ipa"
          curl -L -o frida-gadget-17.3.2-ios-universal.dylib "https://github.com/ColtonDavis/will-work/releases/download/1/frida-gadget-17.3.2-ios-universal.dylib"
          echo "Downloaded files:"
          ls -lh

      - name: Quick verify first bytes
        run: |
          cd work
          echo "IPA head (hex):"; hexdump -C -n 8 crssplay_frida_localpatched.ipa || true
          head4=$(xxd -p -l 4 crssplay_frida_localpatched.ipa || true)
          if [ "$head4" != "504b0304" ]; then
            echo "ERROR: IPA does not look like a ZIP (starts: $head4). Aborting."; exit 2
          fi

      - name: Extract IPA (use ditto for robustness)
        run: |
          cd work
          rm -rf work_unzip || true
          mkdir -p work_unzip
          echo "Extracting with ditto..."
          if ditto -x -k crssplay_frida_localpatched.ipa work_unzip; then
            echo "ditto extraction succeeded."
          else
            echo "ditto failed; trying unzip fallback..."
            unzip -o crssplay_frida_localpatched.ipa -d work_unzip || true
          fi
          echo "Top-level listing:"
          ls -la work_unzip || true
          if [ ! -d work_unzip/Payload ]; then
            echo "ERROR: Payload not found in extracted IPA. Aborting."
            find work_unzip -maxdepth 5 -ls || true
            exit 3
          fi

      - name: Copy Frida dylib into app & inject into dfxm (safe, diagnostic)
        run: |
          set -euo pipefail
          cd work_unzip/Payload
          APP_PATH=$(find . -type d -name "*.app" -print -quit)
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: no .app found in Payload"; find . -maxdepth 3 -ls; exit 1
          fi
          APP_PATH="./${APP_PATH#./}"
          echo "App found: $APP_PATH"
          EXE_PATH="$APP_PATH/dfxm"
          if [ ! -f "$EXE_PATH" ]; then
            echo "WARNING: dfxm not at $EXE_PATH; listing app contents:"
            ls -la "$APP_PATH" || true
            # fallback to CFBundleExecutable
            if [ -f "$APP_PATH/Info.plist" ]; then
              execname=$(defaults read "$APP_PATH/Info.plist" CFBundleExecutable 2>/dev/null || true)
              if [ -n "$execname" ]; then
                EXE_PATH="$APP_PATH/$execname"
                echo "Using CFBundleExecutable fallback: $EXE_PATH"
              fi
            fi
            if [ ! -f "$EXE_PATH" ]; then
              echo "ERROR: executable not found in app bundle. Aborting."; exit 1
            fi
          fi
          echo "Target executable: $EXE_PATH"

          mkdir -p "$APP_PATH/Frameworks"
          if [ -f ../../frida-gadget-17.3.2-ios-universal.dylib ]; then
            cp ../../frida-gadget-17.3.2-ios-universal.dylib "$APP_PATH/Frameworks/"
          else
            echo "ERROR: frida dylib not found at expected location"; ls -la ../.. || true; exit 1
          fi
          chmod 755 "$APP_PATH/Frameworks/frida-gadget-17.3.2-ios-universal.dylib"
          echo "Frameworks contents:"
          ls -la "$APP_PATH/Frameworks"

          # ensure optool exists - try prebuilt then build
          if ! command -v optool >/dev/null 2>&1; then
            OPTZIP="https://github.com/alexzielenski/optool/releases/download/0.1/optool.zip"
            if curl -sSL "$OPTZIP" -o /tmp/optool.zip; then
              unzip -o /tmp/optool.zip -d /tmp/optool_tmp || true
              if [ -f /tmp/optool_tmp/optool ]; then
                sudo mv /tmp/optool_tmp/optool /usr/local/bin/optool
                sudo chmod +x /usr/local/bin/optool
              fi
            fi
          fi
          if ! command -v optool >/dev/null 2>&1; then
            git clone https://github.com/alexzielenski/optool.git /tmp/optool_src
            cd /tmp/optool_src
            make || true
            if [ -f optool ]; then
              sudo mv optool /usr/local/bin/optool
            else
              echo "ERROR: optool not available"; exit 1
            fi
          fi

          echo "Injecting frida gadget into $EXE_PATH"
          sudo /usr/local/bin/optool install -c load -p "@executable_path/Frameworks/frida-gadget-17.3.2-ios-universal.dylib" -t "$EXE_PATH" || { echo "optool failed"; exit 1; }

          # verify injection
          if command -v otool >/dev/null 2>&1; then
            echo "otool -L (filtered):"
            otool -L "$EXE_PATH" | grep -i frida || true
          else
            echo "strings check:"
            strings "$EXE_PATH" | grep -i frida || true
          fi
          echo "Injection step completed."

      - name: Repack IPA
        run: |
          cd work_unzip
          zip -r ../crssplay_frida_patched.ipa Payload
          cd ..
          ls -lh crssplay_frida_patched.ipa || true

      - name: Upload patched IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: crssplay_frida_patched
          path: work/crssplay_frida_patched.ipa
